---

- block:

   - name: Include files matching test_users.yaml
     ansible.builtin.include_vars:
      dir: vars
      files_matching: test_users.yml

   - name: Include files matching test_files.yaml
     ansible.builtin.include_vars:
      dir: vars
      files_matching: test_files.yml

   # create test users
   - name: "Creation of test user's groups"
     ansible.builtin.group:
      name: "{{ item.value.group }}"
      state: present
     loop: "{{ lookup('dict', ansible_created_test_users) }}"
     when: ansible_create_test_users | bool

   # create test users
   - name: "Creation of test users"
     ansible.builtin.user:
      name: "{{ item.value.name }}"
      group: "{{ item.value.group }}"
      comment: "{{ item.value.comment }}"
      password: "{{ item.value.password }}"
      shell: "{{ item.value.shell }}"
     loop: "{{ lookup('dict', ansible_created_test_users) }}"
     when: ansible_create_test_users | bool     

   # create test dirs
   - name: "Creation of empty directories in {{ rh_mountpoint }} IGNORING ERRORS"
     ansible.builtin.file:
      mode: '0777'
      path: "{{ item.value.path }}"
      state: "{{ item.value.state }}"
      modification_time: "{{ item.value.modification_time }}"
      owner: "{{ item.value.owner }}"
      group: "{{ item.value.group }}"
     loop: "{{ lookup('dict', ansible_created_test_dirs) }}"
     ignore_errors: true
     when: ansible_create_test_files | bool

   # ignore errors, though these warrant investigation
   - name: "Create some test files in {{ rh_mountpoint }} - ignore errors, though these warrant investigation"
     community.general.filesize:
      path: "{{ item.value.path }}"
      size: "{{ item.value.size }}"
      attributes: "{{ item.value.attributes }}"
     loop: "{{ lookup('dict', ansible_created_test_files) }}"
     ignore_errors: true
     when: ansible_create_test_files | bool

   # ignore errors a test file may be immutable for instance
   - name: "Enforce properties on test files in {{ rh_mountpoint }} IGNORING ERRORS"
     ansible.builtin.file:
      mode: '0777'
      path: "{{ item.value.path }}"
      state: "{{ item.value.state }}"
      modification_time: "{{ item.value.modification_time }}"
      owner: "{{ item.value.owner }}"
      group: "{{ item.value.group }}"
     loop: "{{ lookup('dict', ansible_created_test_files) }}"
     ignore_errors: true
     when: ansible_create_test_files | bool

   - name: "run robinhood validation, robinhood --test-syntax"
     ansible.builtin.command: robinhood --test-syntax
     ignore_errors: true

   # do a scan once, if requested
   - name: "Command - robinhood --scan --once; ***this may take some time...***"
     ansible.builtin.shell:
      cmd: "robinhood --scan --once"
     when: run_scan_on_ansible_run | bool

   # run rbh-report, if requested
   - name: "Commands - run df and rbh-report commands"
     ansible.builtin.shell:
      cmd: "{{ item }}"
     when: run_rbh_report_on_ansible_run | bool
     register: rbh_report_out
     loop:
      - "df -hT {{ rh_mountpoint }}"
      - "rbh-report -a"
      - "rbh-report --classinfo"

   - name: "Show summary commands outputs"
     ansible.builtin.debug:
      msg: "{{ item.stdout_lines }}"
     loop: "{{ rbh_report_out.results }}"

   - name: "Show hints"
     ansible.builtin.debug:
      msg:
       - "Run scan with:"
       - "robinhood --scan --once OR robinhood --scan --once --detach"
       - "-----------------------"
       - "Run ALL policies with:"
       - "robinhood --run --once"
       - "-----------------------"
       - "Other commands:"
       - "rbh-report"
       - "rbh-du"
       - "rbh-find"
       - "-----------------------"
       - "Aliases for quick access:"
       - "rh_scan_once"
       - "rh_run_once"
       - "rh_syntax"
       - "-----------------------"
       - "Web interface is seen at http://{{ansible_ssh_host}}/robinhood/#"

  become: true

...
