---

# ----------------------- TEST FILES -------------------------------------------------------------------------

# N.B. YYYYMMDDHHMM.SS for modification_time
ansible_created_test_files:
    rh_test_file1:
      file_number: 1
      path: "{{ rh_mountpoint}}/rh_test_file1"
      modification_time: now
      state: touch
      size: 1G
      attributes: ''
    rh_test_file2:
      file_number: 2
      path: "{{ rh_mountpoint}}/rh_test_file2"
      modification_time: 200001011200.00
      state: touch
      size: 500M
      attributes: '+i'
    rh_test_file3:
      file_number: 3
      path: "{{ rh_mountpoint}}/rh_test_file3"
      modification_time: 202301011200.00
      state: touch
      size: 1M
      attributes: ''
    rh_test_file4:
      file_number: 4
      path: "{{ rh_mountpoint}}/rh_test_file4"
      modification_time: now
      state: touch
      size: 1K
      attributes: ''

...
