---

- block:

   - name: "RHEL7 - Install epel-release"
     ansible.builtin.yum:
      name: epel-release
      state: present
      update_cache: true

   - name: "RHEL7 Update all packages"
     ansible.builtin.yum:
      name: '*'
      state: latest
     when: full_package_update | bool

   - name: "RHEL Common - Install robinhood dependencies"
     ansible.builtin.yum:
      name: "{{ rhel_depends }}"
      state: present

   - name: "RHEL7 - **EPEL source** Install robinhood dependencies"
     ansible.builtin.yum:
      name: "{{ rhel_epel_depends }}"
      state: present

   - name: RHEL7 - Install robinhood dependencies
     ansible.builtin.yum:
      name: "{{ rhel7_depends }}"
      state: present

  become: true

...
